"""
Gate sequence  R(theta_k, alpha_k) -> CS_A(r_k) -> CS_B(t_k)   (k = 1..N)
optimized so that the oscillator state after layer k follows the
TIME-OPTIMAL evolution generated by H_opt (vacuum -> finite-energy GKP |0_L>).

Time-optimal evolution
----------------------
H_opt = i w (e^{-i phi}|chi><0| - h.c.)   acts as a rotation in span{|0>,|chi>},
|chi> = |T_perp>/||T_perp||,  |T_perp> = |T> - <0|T>|0>.

With the global phase chosen so that <0|T> = cos(theta0) >= 0:

    |T>      = cos(theta0)|0> + sin(theta0)|chi>
    |g(s)>   = cos(s theta0)|0> + sin(s theta0)|chi>,    s = t/t*  in [0,1]
    |<T|g(s)>|^2 = cos^2((1-s) theta0)

Loss (all oscillator states; qubit traced out)
    L = sum_k w_k [ 1 - sum_q |<g(k/N)|psi_k^q>|^2 ]  + small control regularizers
Matching the pure geodesic state at every layer forces the qubit to
disentangle at every layer and makes the whole Wigner trajectory follow
the H_opt one.

Target (paper Eq. 4):
    |mu_L; alpha,beta,Delta> ~ e^{-Delta^2 n} sum_{m=mu mod 2, l} e^{-i pi m l/2} |m alpha + l beta>

Pure NumPy / SciPy / Matplotlib (+ Pillow).  No JAX.
"""

import argparse
import time
import numpy as np
from scipy.optimize import minimize
from scipy.special import gammaln

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, PillowWriter

# ======================================================================
# COMMAND LINE
# ======================================================================
ap = argparse.ArgumentParser()
ap.add_argument("--D", type=int, default=80, help="Fock cutoff")
ap.add_argument("--N", type=int, default=32, help="number of layers")
ap.add_argument("--Delta", type=float, default=0.35, help="GKP envelope e^{-Delta^2 n}")
ap.add_argument("--alpha", type=float, default=np.sqrt(np.pi / 2), help="lattice vector alpha (real)")
ap.add_argument("--beta_im", type=float, default=np.sqrt(np.pi / 2), help="beta = i*beta_im")
ap.add_argument("--mu", type=int, default=0, help="logical index (0 -> +Z)")
ap.add_argument("--M", type=int, default=10, help="lattice sum range |m|,|l| <= M")
ap.add_argument("--seeds", type=int, default=50)
ap.add_argument("--maxiter", type=int, default=5000)
ap.add_argument("--rng", type=int, default=1)
ap.add_argument("--load", type=str, default=None)
ap.add_argument("--frames", type=int, default=4, help="animation frames per gate")
ap.add_argument("--fps", type=int, default=12)
ap.add_argument("--L", type=float, default=7.0, help="Wigner plot range")
ap.add_argument("--out", type=str, default="gkp_timeopt")
ap.add_argument("--wfinal", type=float, default=5.0, help="extra weight on the last layer")
ap.add_argument("--lambda_control", type=float, default=1e-4)
ap.add_argument("--lambda_rot", type=float, default=1e-5)
ap.add_argument("--K", type=int, default=3, help="R-CS_A-CS_B blocks between geodesic checkpoints")
ap.add_argument("--no_movie", action="store_true", help="only make the Wigner comparison figure")
ap.add_argument("--no_greedy", action="store_true", help="skip greedy layer-by-layer initialization")
args = ap.parse_args()

D, N, Delta = args.D, args.N, args.Delta
K = args.K
NB = N * K          # total number of blocks; geodesic tracked at every K-th block

print("=" * 60)
print(" GKP gate sequence matched to time-optimal H_opt evolution")
print("=" * 60)
print(f"D={D}  checkpoints N={N}  blocks/checkpoint K={K}  total gates={3*NB}  Delta={Delta}  seeds={args.seeds}")
print("=" * 60)

# ======================================================================
# OPERATORS
# ======================================================================
a = np.diag(np.sqrt(np.arange(1, D)), 1).astype(complex)
ad = a.conj().T
A = (a @ a - ad @ ad) / 2
B = 1j * (a @ a + ad @ ad) / 2
wA, VA = np.linalg.eigh(1j * A)
wB, VB = np.linalg.eigh(1j * B)
VAh, VBh = VA.conj().T, VB.conj().T


def expA(c, x):
    return VA @ (np.exp(-1j * c * wA) * (VAh @ x))


def expB(c, x):
    return VB @ (np.exp(-1j * c * wB) * (VBh @ x))


sx = np.array([[0, 1], [1, 0]], dtype=complex)
sy = np.array([[0, -1j], [1j, 0]], dtype=complex)
I2 = np.eye(2, dtype=complex)


def rot(theta, alpha):
    n = np.cos(alpha) * sx + np.sin(alpha) * sy
    return np.cos(theta / 2) * I2 - 1j * np.sin(theta / 2) * n


def hermite(x):
    H = np.zeros((D, len(x)))
    H[0] = np.pi ** (-0.25) * np.exp(-x**2 / 2)
    if D > 1:
        H[1] = np.sqrt(2) * x * H[0]
    for n in range(2, D):
        H[n] = np.sqrt(2 / n) * x * H[n - 1] - np.sqrt((n - 1) / n) * H[n - 2]
    return H


# ======================================================================
# TARGET: paper Eq. (4)
# ======================================================================
def build_target(Dfock, alpha, beta, Dl, mu, M):
    n = np.arange(Dfock)
    lognf = 0.5 * gammaln(n + 1)
    vec = np.zeros(Dfock, dtype=complex)
    for m in range(-M, M + 1):
        if (m - mu) % 2:
            continue
        for l in range(-M, M + 1):
            g = m * alpha + l * beta
            ph = np.exp(-1j * np.pi * m * l / 2)
            if abs(g) < 1e-14:
                vec[0] += ph
                continue
            # e^{-|g|^2/2} g^n / sqrt(n!)   (computed in logs for stability)
            logamp = -abs(g) ** 2 / 2 + n * np.log(abs(g)) - lognf
            vec += ph * np.exp(logamp + 1j * n * np.angle(g))
    vec *= np.exp(-Dl**2 * n)
    return vec


beta = 1j * args.beta_im
Tbig = build_target(2 * D, args.alpha, beta, Delta, args.mu, args.M)
Tbig /= np.linalg.norm(Tbig)
print(f"Target weight inside cutoff D={D}: {np.sum(np.abs(Tbig[:D])**2):.8f}")
T = Tbig[:D].copy()
T /= np.linalg.norm(T)

# ======================================================================
# TIME-OPTIMAL GEODESIC
# ======================================================================
vac = np.zeros(D, dtype=complex)
vac[0] = 1.0
c_raw = np.vdot(vac, T)
T = T * np.exp(-1j * np.angle(c_raw))          # global phase: <0|T> >= 0
c0 = float(np.real(np.vdot(vac, T)))
theta0 = np.arccos(np.clip(c0, -1, 1))
chi = T - c0 * vac
chi /= np.linalg.norm(chi)


def geo_state(s):
    return np.cos(s * theta0) * vac + np.sin(s * theta0) * chi


GEO = np.array([geo_state(k / N) for k in range(N + 1)])          # (N+1, D)
Fgeo_T = np.cos(theta0 * (1 - np.arange(N + 1) / N)) ** 2          # fidelity of geodesic with T
print(f"|<0|T>|^2 = {c0**2:.4e}   theta0 = {theta0:.4f} rad   (t* = theta0/omega)")
print()

# explicit H_opt (omega=1, phi=0), for reference / saving
H_opt = 1j * (np.outer(chi, vac.conj()) - np.outer(vac, chi.conj()))
np.save(f"{args.out}_Hopt_D{D}.npy", H_opt)

# ======================================================================
# CIRCUIT
# ======================================================================
def init_state():
    psi = np.zeros((2, D), dtype=complex)
    psi[0, 0] = 1.0
    return psi


def apply_layer(psi, r, t, theta, alpha):
    p1 = rot(theta, alpha) @ psi
    p2 = np.stack([expA(r, p1[0]), expA(-r, p1[1])])
    return np.stack([expB(t, p2[0]), expB(-t, p2[1])])


def forward(P):
    P = P.reshape(NB, 4)
    psi = init_state()
    states, cache = [psi.copy()], []
    for r, t, theta, alpha in P:
        psi0 = psi
        R = rot(theta, alpha)
        psi1 = R @ psi0
        psi2 = np.stack([expA(r, psi1[0]), expA(-r, psi1[1])])
        psi3 = np.stack([expB(t, psi2[0]), expB(-t, psi2[1])])
        cache.append((psi0, psi2, psi3, R))
        psi = psi3
        states.append(psi.copy())
    return psi, states, cache


def fid_with(g, psi):
    """oscillator fidelity with pure state g, qubit traced out"""
    return abs(np.vdot(g, psi[0])) ** 2 + abs(np.vdot(g, psi[1])) ** 2


def purity_of(psi):
    rq = psi @ psi.conj().T
    return float(np.real(np.trace(rq @ rq)))


# ======================================================================
# REGULARIZERS
# ======================================================================
def control_smoothness(P):
    if NB <= 1:
        return 0.0
    d = P[1:] - P[:-1]
    d[:, 3] = (d[:, 3] + np.pi) % (2 * np.pi) - np.pi
    return np.sum(d**2)


def control_smoothness_grad(P):
    G = np.zeros_like(P)
    d = P[1:] - P[:-1]
    d[:, 3] = (d[:, 3] + np.pi) % (2 * np.pi) - np.pi
    G[:-1] -= 2 * d
    G[1:] += 2 * d
    return G


# ======================================================================
# ADJOINT (per layer)
# ======================================================================
def add_layer_gradient(k, lam, P, cache, G):
    r, t, theta, alpha = P[k]
    psi0, psi2, psi3, R = cache[k]

    G[k, 1] += 2 * np.real(np.vdot(lam[0], B @ psi3[0]) - np.vdot(lam[1], B @ psi3[1]))
    lam = np.stack([expB(-t, lam[0]), expB(t, lam[1])])

    G[k, 0] += 2 * np.real(np.vdot(lam[0], A @ psi2[0]) - np.vdot(lam[1], A @ psi2[1]))
    lam = np.stack([expA(-r, lam[0]), expA(r, lam[1])])

    ns = np.cos(alpha) * sx + np.sin(alpha) * sy
    dR_dtheta = -0.5j * ns @ R
    dR_dalpha = -1j * np.sin(theta / 2) * (-np.sin(alpha) * sx + np.cos(alpha) * sy)
    G[k, 2] += 2 * np.real(np.sum(np.conj(lam) * (dR_dtheta @ psi0)))
    G[k, 3] += 2 * np.real(np.sum(np.conj(lam) * (dR_dalpha @ psi0)))
    return R.conj().T @ lam


# ======================================================================
# OBJECTIVE: track the geodesic state at every layer
# ======================================================================
wk = np.ones(N + 1) / N
wk[N] = args.wfinal
wk[0] = 0.0


def track_loss_grad(p):
    P = p.reshape(NB, 4)
    psiF, states, cache = forward(P)

    loss = 0.0
    coef = np.zeros(NB + 1)
    for j in range(1, N + 1):
        k = j * K
        loss += wk[j] * (1.0 - fid_with(GEO[j], states[k]))
        coef[k] = -wk[j]                               # dL/dF at checkpoint

    loss += args.lambda_control * control_smoothness(P)
    loss += args.lambda_rot * np.sum(P[:, 2] ** 2)

    G = np.zeros((NB, 4))
    lam = np.zeros((2, D), dtype=complex)
    for k in reversed(range(NB)):
        if coef[k + 1] != 0.0:
            g = GEO[(k + 1) // K]
            st = states[k + 1]
            c0_, c1_ = np.vdot(g, st[0]), np.vdot(g, st[1])
            lam += coef[k + 1] * np.stack([g * c0_, g * c1_])
        lam = add_layer_gradient(k, lam, P, cache, G)

    G += args.lambda_control * control_smoothness_grad(P)
    G[:, 2] += args.lambda_rot * 2 * P[:, 2]
    return loss, G.ravel()


# gradient check
rc = np.random.default_rng(123)
pc = rc.normal(0, 0.2, 4 * NB)
l0, g0 = track_loss_grad(pc)
err = 0.0
for j in rc.choice(4 * NB, 6, replace=False):
    pp = pc.copy()
    pp[j] += 1e-6
    err = max(err, abs((track_loss_grad(pp)[0] - l0) / 1e-6 - g0[j]))
print(f"gradient check (tracking loss): max error = {err:.3e}\n")


# ======================================================================
# GREEDY INITIALIZATION: layer k maximizes overlap with g(k/N)
# ======================================================================
def greedy_init(rng):
    psi = init_state()
    P = np.zeros((NB, 4))
    prev = np.zeros(4)
    for k in range(1, NB + 1):
        g = geo_state(k / NB)
        best = None
        for trial in range(4):
            x0 = prev.copy() if trial == 0 else prev + rng.normal(0, 0.1, 4)
            res = minimize(lambda x: 1 - fid_with(g, apply_layer(psi, *x)),
                           x0, method="BFGS", options={"maxiter": 60})
            if best is None or res.fun < best.fun:
                best = res
        P[k - 1] = best.x
        prev = best.x
        psi = apply_layer(psi, *best.x)
    return P.ravel()


# ======================================================================
# OPTIMIZATION
# ======================================================================
def summarize(x):
    _, st, _ = forward(x)
    Fg = np.array([fid_with(GEO[j], st[j * K]) for j in range(N + 1)])
    st = [st[j * K] for j in range(N + 1)]
    return Fg, st


if args.load:
    best_x = np.load(args.load)
else:
    rng = np.random.default_rng(args.rng)
    best = None
    for seed in range(args.seeds):
        t_start = time.time()
        if seed == 0 and not args.no_greedy:
            p0 = greedy_init(rng)
            tag = "greedy"
        else:
            p0 = np.column_stack([rng.normal(0, 0.15, NB), rng.normal(0, 0.15, NB),
                                  rng.normal(0, 0.1, NB), rng.normal(0, 0.05, NB)]).ravel()
            tag = "random"
        res = minimize(track_loss_grad, p0, jac=True, method="L-BFGS-B",
                       options={"maxiter": args.maxiter, "maxfun": 2 * args.maxiter,
                                "ftol": 1e-13, "gtol": 1e-8, "maxls": 30})
        Fg, st = summarize(res.x)
        FT = fid_with(T, st[N])
        print(f"seed {seed:2d} ({tag:6s}): loss={res.fun:.3e}  min_k F_geo={Fg[1:].min():.5f}  "
              f"F_target={FT:.6f}  it={res.nit}  {time.time()-t_start:.1f}s", flush=True)
        if best is None or res.fun < best["loss"]:
            best = {"loss": res.fun, "x": res.x.copy()}
        if Fg[1:].min() > 0.995:
            print("\nReached >0.995 geodesic fidelity at every layer.\n")
            break
    best_x = best["x"]
    np.save(f"{args.out}_params_D{D}_N{N}_K{K}_Delta{Delta}.npy", best_x)

# ======================================================================
# REPORT
# ======================================================================
Fg, statesF = summarize(best_x)
print("=" * 60)
print(" FINAL RESULT")
print("=" * 60)
print(f"F(target)      = {fid_with(T, statesF[N]):.8f}")
print(f"qubit purity   = {purity_of(statesF[N]):.8f}")
print(f"min F to geodesic over layers = {Fg[1:].min():.6f}")
print("\ncheckpoint   F_to_geodesic   F_to_target   F_geodesic_to_target   qubit_purity")
for k in range(N + 1):
    print(f"{k:4d}    {Fg[k]:.6f}      {fid_with(T, statesF[k]):.6f}      {Fgeo_T[k]:.6f}"
          f"            {purity_of(statesF[k]):.6f}")
total_time = np.sum(np.abs(best_x.reshape(NB, 4)[:, :3]))
print(f"\ncircuit 'time' sum(|r|+|t|+|theta|) = {total_time:.4f}")
print("\nParameters [r, t, theta, alpha]:")
print(np.array2string(best_x.reshape(NB, 4), precision=6, suppress_small=True))

np.savetxt(f"{args.out}_trajectory.txt",
           np.column_stack([np.arange(N + 1), Fg,
                            [fid_with(T, statesF[k]) for k in range(N + 1)], Fgeo_T]),
           header="layer F_to_geodesic F_circuit_to_target F_geodesic_to_target")

fig0, ax0 = plt.subplots(figsize=(5.5, 3.8))
ax0.plot(np.arange(N + 1), Fgeo_T, "k--", label=r"H$_{opt}$: $\cos^2[\theta_0(1-k/N)]$")
ax0.plot(np.arange(N + 1), [fid_with(T, statesF[k]) for k in range(N + 1)], "o-", ms=3, label="circuit")
ax0.set_xlabel("layer k")
ax0.set_ylabel("fidelity with target")
ax0.legend()
fig0.tight_layout()
fig0.savefig(f"{args.out}_fidelity_vs_geodesic.png", dpi=150)
plt.close(fig0)

# ======================================================================
# WIGNER
# ======================================================================
L = args.L
xw = np.linspace(-L, L, 201)
pw = np.linspace(-L, L, 201)
hw = xw[1] - xw[0]
nw = len(xw)
Hw = hermite(xw)
kk = np.arange(-(nw - 1), nw)
Eph = np.exp(2j * np.outer(pw, kk * hw))
ii = np.arange(nw)
ip = ii[None, :] + kk[:, None]
im = ii[None, :] - kk[:, None]
valid = (ip >= 0) & (ip < nw) & (im >= 0) & (im < nw)
ipc = np.clip(ip, 0, nw - 1)
imc = np.clip(im, 0, nw - 1)


def wigner(psi):
    W = np.zeros((len(pw), nw))
    for s in range(2):
        f = psi[s] @ Hw
        M_ = np.conj(f[ipc]) * f[imc] * valid
        W += np.real(Eph @ M_)
    return W * hw / np.pi


# ======================================================================
# WIGNER COMPARISON: circuit vs time-optimal H_opt at every layer
# ======================================================================
dA = hw * hw
zero_ = np.zeros(D, dtype=complex)
Wc_l = [wigner(statesF[k]) for k in range(N + 1)]
Wg_l = [wigner(np.stack([GEO[k], zero_])) for k in range(N + 1)]
Wt_l = wigner(np.stack([T, zero_]))

ov = np.array([2 * np.pi * np.sum(Wc_l[k] * Wg_l[k]) * dA for k in range(N + 1)])      # Tr(rho_c rho_g)
nrm = np.array([np.sqrt(2 * np.pi * np.sum(Wg_l[k] ** 2) * dA) for k in range(N + 1)])  # sqrt(purity_g)=1
pur = np.array([2 * np.pi * np.sum(Wc_l[k] ** 2) * dA for k in range(N + 1)])           # purity of circuit oscillator state
rel = np.array([np.sqrt(np.sum((Wc_l[k] - Wg_l[k]) ** 2) / np.sum(Wg_l[k] ** 2)) for k in range(N + 1)])
wmax = max(np.abs(np.array(Wc_l)).max(), np.abs(np.array(Wg_l)).max())

cols = [0, N // 4, N // 2, (3 * N) // 4, N]
figc = plt.figure(figsize=(14, 11))
gs = figc.add_gridspec(4, len(cols), height_ratios=[1, 1, 1, 0.9], hspace=0.35, wspace=0.12)
kw2 = dict(extent=[-L, L, -L, L], origin="lower", cmap="RdBu_r", aspect="equal")
for j, k in enumerate(cols):
    a0 = figc.add_subplot(gs[0, j]); a1 = figc.add_subplot(gs[1, j]); a2 = figc.add_subplot(gs[2, j])
    a0.imshow(Wc_l[k], vmin=-0.35, vmax=0.35, **kw2)
    a1.imshow(Wg_l[k], vmin=-0.35, vmax=0.35, **kw2)
    a2.imshow(Wc_l[k] - Wg_l[k], vmin=-0.35, vmax=0.35, **kw2)
    a0.set_title(f"layer {k}/{N}  (t/t_f={k/N:.2f})", fontsize=10)
    for aa in (a0, a1, a2):
        aa.set_xticks([]); aa.set_yticks([])
    if j == 0:
        a0.set_ylabel("circuit"); a1.set_ylabel("H_opt"); a2.set_ylabel("circuit - H_opt")
    a2.set_xlabel(f"F={ov[k]:.3f}", fontsize=9)
axm = figc.add_subplot(gs[3, :])
kx = np.arange(N + 1)
axm.plot(kx, Fg, "o-", ms=3, label=r"state fidelity $F=\sum_q|\langle g_k|\psi_k^q\rangle|^2$")
axm.plot(kx, ov, "s--", ms=3, label=r"Wigner overlap $2\pi\int W_c W_g$ (should equal $F$)")
axm.plot(kx, pur, "^-", ms=3, label="circuit oscillator purity")
axm.plot(kx, 1 - rel, "d:", ms=3, label=r"$1-\|W_c-W_g\|_2/\|W_g\|_2$")
axm.set_xlabel("layer k"); axm.set_ylabel("match"); axm.set_ylim(min(0, (1 - rel).min()) - 0.05, 1.05)
axm.grid(alpha=0.3); axm.legend(fontsize=8, loc="lower center", ncol=2)
figc.suptitle("Wigner trajectory: gate sequence vs time-optimal H_opt evolution", y=0.92)
cmp_file = f"{args.out}_wigner_match.png"
figc.savefig(cmp_file, dpi=130, bbox_inches="tight")
plt.close(figc)
print(f"Wigner comparison figure: {cmp_file}")
print("layer  F_state  Wigner_overlap  purity_c  rel_L2_err")
for k in range(0, N + 1, max(1, N // 12)):
    print(f"{k:4d}   {Fg[k]:.4f}   {ov[k]:.4f}        {pur[k]:.4f}    {rel[k]:.4f}")
if args.no_movie:
    raise SystemExit


def path_states(P, m):
    """every gate interpolated; s = fraction of the geodesic at that point"""
    P = P.reshape(NB, 4)
    psi = init_state()
    out = [("vacuum", 0, psi.copy(), 0.0)]
    for k, (r, t, theta, alpha) in enumerate(P):
        for g, name in enumerate(["qubit rotation", "CS_A squeezing", "CS_B squeezing"]):
            for f in np.linspace(0, 1, m + 1)[1:]:
                if g == 0:
                    st = rot(f * theta, alpha) @ psi
                elif g == 1:
                    st = np.stack([expA(f * r, psi[0]), expA(-f * r, psi[1])])
                else:
                    st = np.stack([expB(f * t, psi[0]), expB(-f * t, psi[1])])
                s = (k + (g + f) / 3) / NB
                out.append((name, k + 1, st, s))
            if g == 0:
                psi = rot(theta, alpha) @ psi
            elif g == 1:
                psi = np.stack([expA(r, psi[0]), expA(-r, psi[1])])
            else:
                psi = np.stack([expB(t, psi[0]), expB(-t, psi[1])])
    return out


frames = path_states(best_x, args.frames)
frames += [frames[-1]] * (2 * args.fps)
print(f"\nComputing {len(frames)} Wigner frames...")

zero = np.zeros(D, dtype=complex)
Wt = wigner(np.stack([T, zero]))
Wc, Wg = [], []
wig_err = []
for i, (lab, lay, psi, s) in enumerate(frames):
    if i % 20 == 0:
        print(f"  frame {i+1}/{len(frames)}", flush=True)
    wc = wigner(psi)
    wg = wigner(np.stack([geo_state(min(s, 1.0)), zero]))
    Wc.append(wc)
    Wg.append(wg)
    wig_err.append(np.sqrt(np.sum((wc - wg) ** 2)) * hw * np.sqrt(1) / 1.0)

# Wigner L2 distance along the layer endpoints
layer_idx = [i for i, f in enumerate(frames[:-2 * args.fps]) if i == 0 or i % (3 * args.frames * K) == 0]
print("Wigner L2 distance (circuit vs H_opt) at layer ends:",
      np.array2string(np.array([wig_err[i] for i in layer_idx]), precision=3))

vmax = 0.35
fig, ax = plt.subplots(1, 3, figsize=(13, 4.4), sharey=True)
ext = [-L, L, -L, L]
kw = dict(extent=ext, origin="lower", cmap="RdBu_r", vmin=-vmax, vmax=vmax, aspect="equal")
im0 = ax[0].imshow(Wc[0], **kw)
im1 = ax[1].imshow(Wg[0], **kw)
ax[2].imshow(Wt, **kw)
ax[2].set_title(r"Target GKP $|0_L\rangle$")
ax[1].set_title(r"Time-optimal $H_{opt}$ evolution")
for axx in ax:
    axx.set_xlabel("x")
ax[0].set_ylabel("p")
fig.colorbar(im0, ax=ax, label="W(x,p)", shrink=0.85)
title = ax[0].set_title("", fontsize=9)


def update(i):
    lab, lay, psi, s = frames[i]
    im0.set_data(Wc[i])
    im1.set_data(Wg[i])
    sg = min(s, 1.0)
    title.set_text(f"circuit: block {lay}/{NB}, {lab}\n"
                   f"F(target)={fid_with(T, psi):.3f}   F(H_opt state)={fid_with(geo_state(sg), psi):.3f}")
    return im0, im1, title


anim = FuncAnimation(fig, update, frames=len(frames), blit=False)
gif_file = f"{args.out}_wigner_compare.gif"
anim.save(gif_file, writer=PillowWriter(fps=args.fps), dpi=80)
update(len(frames) - 1)
png_file = f"{args.out}_wigner_final.png"
fig.savefig(png_file, dpi=150, bbox_inches="tight")
plt.close(fig)

# snapshot panel: circuit (top) vs H_opt (bottom) at t/t_f = 0, 1/3, 2/3, 1
snaps = [0.0, 1 / 3, 2 / 3, 1.0]
fig2, ax2 = plt.subplots(2, 4, figsize=(12, 6), sharex=True, sharey=True)
body = frames[:-2 * args.fps]
for j, sv in enumerate(snaps):
    i = int(np.argmin([abs(f[3] - sv) for f in body]))
    ax2[0, j].imshow(Wc[i], **kw)
    ax2[1, j].imshow(Wg[i], **kw)
    ax2[0, j].set_title(rf"$t/t_f={sv:.2f}$")
ax2[0, 0].set_ylabel("circuit  p")
ax2[1, 0].set_ylabel(r"$H_{opt}$  p")
fig2.tight_layout()
snap_file = f"{args.out}_snapshots.png"
fig2.savefig(snap_file, dpi=150)
plt.close(fig2)

print("\n" + "=" * 60)
print(" OUTPUT")
print("=" * 60)
print(f"Final F(target):        {fid_with(T, statesF[N]):.8f}")
print(f"Comparison GIF:         {gif_file}")
print(f"Final Wigner PNG:       {png_file}")
print(f"Snapshot panel:         {snap_file}")
print(f"Fidelity vs geodesic:   {args.out}_fidelity_vs_geodesic.png")
print("=" * 60)
